const version = '3.2';
const RECETTES = {
    plats: [
        {
            id: 1,
            nom: 'Poulet aux petits pois en sauce, riz blanc',
            emoji: '🍗',
            description: 'Poulet mijote avec petits pois servi avec du riz blanc.',
            temps: 35,
            difficulte: 'facile',
            humeurs: ['fatiguée', 'stressée', 'sportive', 'curieuse'],
            tags: ['riz', 'mijote', 'familial'],
            ingredients: [
                'Poulet',
                'Petits pois',
                'Oignon',
                'Tomates',
                'Riz blanc',
                'Epices : coriandre, cumin, paprika, herbes de Provence, poivre, piment vert',
            ],
        },
        {
            id: 2,
            nom: 'Sauce arachide a la viande, riz blanc',
            emoji: '\u{1F969}',
            description: 'Viande de boeuf ou de poulet en sauce arachide onctueuse avec riz blanc.',
            temps: 45,
            difficulte: 'moyen',
            humeurs: ['sportive', 'joyeuse', 'curieuse'],
            tags: ['riz', 'arachide', 'tradition'],
            ingredients: [
                'Viande de boeuf ou de poulet',
                "Pate d'arachide",
                'Oignon',
                'Tomates',
                'Riz blanc',
                'Epices : coriandre, cumin, paprika, poivre, piment vert',
            ],
        },
        {
            id: 3,
            nom: "Attieke au poisson",
            emoji: '\u{1F420}',
            description: 'Poisson assaisonne servi avec Attieke. Bananes plantain dorees en option.',
            temps: 35,
            difficulte: 'moyen',
            humeurs: ['curieuse', 'joyeuse', 'amoureuse'],
            tags: ['poisson', 'plantain', 'complet'],
            ingredients: [
                'Poisson',
                'Attieke',
                'Bananes plantain (en option)',
                'Citron',
                'Ail',
                'Huile',
                'Epices : coriandre, paprika, poivre, piment vert',
            ],
        },
        {
            id: 4,
            nom: 'Haricots en sauce a la viande',
            emoji: '\u{1F372}',
            description: 'Haricots mijotes avec viande de boeuf ou de poulet et base de tomates. Servi avec riz et/ou pain.',
            temps: 45,
            difficulte: 'facile',
            humeurs: ['sportive', 'stressée'],
            tags: ['mijote', 'proteines', 'familial'],
            ingredients: [
                'Haricots',
                'Viande de boeuf ou de poulet',
                'Oignon',
                'Tomates',
                'Ail',
                'Epices : coriandre, paprika, poivre, piment vert',
            ],
        },
        {
            id: 5,
            nom: 'Lentilles jaunes ou noires, baguette croustillante',
            emoji: '\u{1FAD8}',
            description: 'Lentilles fondantes bien assaisonnees avec baguette croustillante.',
            temps: 30,
            difficulte: 'très facile',
            humeurs: ['fatiguée', 'stressée', 'sportive'],
            tags: ['economique', 'proteines', 'reconfort'],
            ingredients: [
                'Lentilles jaunes ou noires',
                'Oignon',
                'Ail',
                'Tomates',
                'Baguette',
                'Epices : coriandre, cumin, paprika, poivre',
            ],
        },
        {
            id: 6,
            nom: 'Salade de legumes frais et oeufs durs',
            emoji: '\u{1F957}',
            description: 'Salade fraiche de legumes croquants avec des oeufs durs, simple et coloree.',
            temps: 15,
            difficulte: 'très facile',
            humeurs: ['fatiguée', 'joyeuse', 'sportive', 'stressée'],
            tags: ['leger', 'frais', 'rapide'],
            ingredients: [
                'Tomates',
                'Concombre',
                'Laitue',
                'Oignon',
                'Citron',
                'Oeufs durs',
                'Mayonnaise',
                'Olives',
            ],
        },
        {
            id: 7,
            nom: 'Fah-fah',
            emoji: '\u{1F963}',
            description: 'Soupe de viande et legumes, servie avec du riz blanc et salade en option.',
            temps: 60,
            difficulte: 'moyen',
            humeurs: ['curieuse', 'joyeuse'],
            tags: ['tradition', 'riz', 'reconfort'],
            ingredients: [
                "Viande de boeuf ou d'agneau",
                'Tomates',
                'Carotte',
                'Oignon',
                'Pommes de terre',
                'Chou',
                'Poireaux',
                'Riz blanc',
                'Celeri',
                'Epices : coriandre, cumin, herbes de Provence, poivre, piment vert',
            ],
        },
        {
            id: 8,
            nom: 'Quiche au poulet ou a la viande hachee',
            emoji: '\u{1F9C7}',
            description: 'Quiche maison genereuse avec poulet ou viande hachee.',
            temps: 45,
            difficulte: 'facile',
            humeurs: ['joyeuse', 'amoureuse'],
            tags: ['four', 'familial', 'partage'],
            ingredients: [
                'Pate brisee ou faite maison',
                'Poulet ou viande hachee',
                'Oeufs',
                'Creme',
                'Oignon',
                'Legumes',
                'Epices : cumin, herbes de Provence, poivre',
            ],
        },
        {
            id: 9,
            nom: 'Pâtes à la bolognaise maison',
            emoji: '\u{1F35D}',
            description: 'Pates a la bolognaise maison, riches et reconfortantes.',
            temps: 30,
            difficulte: 'facile',
            humeurs: ['fatiguée', 'joyeuse', 'amoureuse'],
            tags: ['pates', 'tomate', 'incontournable'],
            ingredients: [
                'Pates',
                'Viande hachee',
                'Tomates',
                'Oignon',
                'Huile',
                'Legumes',
                'Epices : herbes de Provence, paprika, poivre',
            ],
        },
        {
            id: 10,
            nom: 'Pâtes à la crème fraîche et poulet',
            emoji: '\u{1F35C}',
            description: 'Pâtes crémeuses au poulet, rapides et savoureuses.',
            temps: 25,
            difficulte: 'facile',
            humeurs: ['fatiguée', 'amoureuse', 'joyeuse'],
            tags: ['pâtes', 'crémeux', 'express'],
            ingredients: [
                'Pâtes',
                'Poulet',
                'Creme fraiche',
                'Ail',
                'Parmesan',
                'Epices : herbes de Provence, paprika, poivre',
            ],
        },
        {
            id: 11,
            nom: 'Haricots en sauce, baguette',
            emoji: '\u{1F958}',
            description: 'Haricots en sauce tomate servis avec baguette croustillante.',
            temps: 35,
            difficulte: 'facile',
            humeurs: ['stressée', 'fatiguée', 'sportive'],
            tags: ['vegetal', 'economique', 'reconfort'],
            ingredients: [
                'Haricots',
                'Tomates',
                'Oignon',
                'Ail',
                'Baguette',
                'Epices : coriandre, cumin, paprika, poivre',
            ],
        },
        {
            id: 12,
            nom: 'Tacos maison au poulet ou boeuf hache',
            emoji: '\u{1F32E}',
            description: 'Tacos gourmands au poulet ou boeuf hache avec garniture maison.',
            temps: 25,
            difficulte: 'facile',
            humeurs: ['joyeuse', 'amoureuse', 'curieuse'],
            tags: ['street food', 'convivial', 'rapide'],
            ingredients: [
                'Galettes tortillas',
                'Poulet ou boeuf hache',
                'Emmental rape',
                'Cheddar',
                'Frites',
                'Sauces : algerienne, harissa, ketchup, mayonnaise',
                'Epices : coriandre, cumin, paprika, poivre, piment vert',
            ],
        },
        {
            id: 13,
            nom: 'Burger maison',
            emoji: '\u{1F354}',
            description: 'Burger maison genereux, croustillant et fondant.',
            temps: 20,
            difficulte: 'très facile',
            humeurs: ['joyeuse', 'sportive', 'fatiguée'],
            tags: ['rapide', 'plaisir', 'convivial'],
            ingredients: [
                'Pains burger maison',
                'Steak hache maison',
                'Cheddar',
                'Tomates',
                'Salade',
                'Sauces : algerienne, harissa, ketchup, mayonnaise',
                'Epices : paprika, poivre',
            ],
        },
        {
            id: 14,
            nom: 'Pizza maison',
            emoji: '\u{1F355}',
            description: 'Pizza maison doree avec garniture au choix.',
            temps: 30,
            difficulte: 'facile',
            humeurs: ['joyeuse', 'amoureuse', 'fatiguée'],
            tags: ['four', 'partage', 'incontournable'],
            ingredients: [
                'Pate a pizza ou faite maison',
                'Viande au choix',
                'Tomates',
                'Fromages',
                'Olives',
                'Epices : herbes de Provence, paprika, poivre',
            ],
        },
        {
            id: 15,
            nom: 'Poulets frits croustillants',
            emoji: '\u{1F356}',
            description: "Poulet frit croustillant a l'exterieur et tendre a l'interieur.",
            temps: 40,
            difficulte: 'moyen',
            humeurs: ['joyeuse', 'amoureuse'],
            tags: ['croustillant', 'plaisir', 'partage'],
            ingredients: [
                'Poulet',
                'Farine',
                'Oeufs',
                'Chapelure',
                'Huile',
                'Epices : coriandre, cumin, paprika, poivre, piment vert',
            ],
        },
        {
            id: 16,
            nom: 'Nuggets de poulet maison',
            emoji: '\u{1F357}',
            description: 'Nuggets de poulet maison croustillants et moelleux.',
            temps: 30,
            difficulte: 'facile',
            humeurs: ['joyeuse', 'fatiguée', 'sportive'],
            tags: ['rapide', 'croustillant', 'enfants'],
            ingredients: [
                'Poulet',
                'Farine',
                'Oeufs',
                'Chapelure',
                'Huile',
                'Epices : herbes de Provence, paprika, poivre',
            ],
        },
        {
            id: 17,
            nom: 'Poisson et bananes plantain',
            emoji: '\u{1F41F}',
            description: 'Poisson assaisonne servi avec bananes plantain dorees.',
            temps: 35,
            difficulte: 'moyen',
            humeurs: ['curieuse', 'joyeuse', 'amoureuse'],
            tags: ['poisson', 'plantain', 'complet'],
            ingredients: [
                'Poisson',
                'Bananes plantain',
                'Citron',
                'Ail',
                'Huile',
                'Epices : coriandre, paprika, poivre, piment vert',
            ],
        },
    ],

    entrees: [
        {
            id: 101,
            nom: 'Nems au poulet ou a la viande',
            emoji: '\u{1F95F}',
            description: 'Nems croustillants farcis au poulet ou a la viande.',
            temps: 30,
            difficulte: 'moyen',
            envies: ['festif', 'chaud'],
            tags: ['apero', 'croustillant', 'partage'],
            ingredients: [
                'Galettes de riz',
                'Poulet ou viande',
                'Carotte',
                'Vermicelles',
                'Oignon',
                'Epices : coriandre, poivre, piment vert',
            ],
        },
        {
            id: 102,
            nom: 'Brick au poulet ou a la viande',
            emoji: '\u{1FAD3}',
            description: 'Brick croustillante farcie au poulet ou a la viande.',
            temps: 20,
            difficulte: 'facile',
            envies: ['chaud', 'express', 'festif'],
            tags: ['entree chaude', 'rapide', 'convivial'],
            ingredients: [
                'Feuilles de brick',
                'Poulet ou viande',
                'Persil',
                'Oeuf',
                'Oignon',
                'Epices : coriandre, cumin, poivre',
            ],
        },
        {
            id: 103,
            nom: 'Samoussa viande hachee ou poulet',
            emoji: '\u{1F53A}',
            description: 'Samoussas croustillants, a la viande hachee ou au poulet.',
            temps: 28,
            difficulte: 'moyen',
            envies: ['festif', 'express'],
            tags: ['finger food', 'partage', 'apero'],
            ingredients: [
                'Feuilles de brick',
                'Viande hachee ou poulet',
                'Oignon',
                'Persil',
                'Ail',
                'Epices : coriandre, cumin, poivre, piment vert',
            ],
        },
        {
            id: 104,
            nom: 'Salade de carottes râpées',
            emoji: '🥕',
            description: 'Carottes râpées assaisonnées au citron, cumin et coriandre fraîche.',
            temps: 10,
            difficulte: 'très facile',
            envies: ['frais', 'express'],
            tags: ['frais', 'rapide', 'enfants'],
            ingredients: [
                'Carottes',
                'Citron',
                'Ail',
                'Persil ou coriandre',
                'Huile d\'olive',
                'Cumin, sel, poivre'
            ],
        },
        {
            id: 107,
            nom: 'Toast avocat au citron',
            emoji: '🥑',
            description: 'Pain grillé tartiné d\'avocat écrasé, citron et piment doux. Prêt en moins de 10 minutes.',
            temps: 8,
            difficulte: 'très facile',
            envies: ['frais', 'express'],
            tags: ['rapide', 'léger', 'moderne'],
            ingredients: [
                'Pain de mie ou baguette',
                'Avocat',
                'Citron',
                'Piment doux ou paprika',
                'Sel',
                'Huile d\'olive'
            ],
        },
    ],

    desserts: [
                {
            id: 208,
            nom: 'Dabo gateau avec graines de nigelle',
            emoji: '\u{1F35E}',
            description: 'Gateau dabo a la nigelle, moelleux et parfume.',
            temps: 60,
            difficulte: 'moyen',
            textures: ['moelleux'],
            tags: ['gateau', 'tradition', 'brunch'],
            ingredients: ['Farine', 'Levure', 'Sucre', 'Lait', "Jaunes d'oeufs", 'Graines de nigelle'],
        },
        {
            id: 201,
            nom: 'Salade de fruits frais',
            emoji: '\u{1F353}',
            description: 'Melange de fruits frais de saison, leger et parfume.',
            temps: 15,
            difficulte: 'très facile',
            textures: ['frais', 'juteux'],
            tags: ['dessert frais', 'leger', 'fruite'],
            ingredients: [
                'Fruits frais au choix : kiwi, banane, fraise, mangue, ananas, pasteque, raisin, melon',
                'Jus de citron ou menthe pour parfumer',
                'Sucre vanille',
            ],
        },
        {
            id: 202,
            nom: 'Crepes maison',
            emoji: '\u{1F95E}',
            description: 'Crepes maison moelleuses, parfaites au gouter.',
            temps: 40,
            difficulte: 'très facile',
            textures: ['moelleux'],
            tags: ['creperie', 'gouter', 'classique'],
            ingredients: ['Farine', 'Oeufs', 'Lait', 'Sucre', 'Huile', 'Sel'],
        },
        {
            id: 203,
            nom: 'Gaufres moelleuses',
            emoji: '\u{1F9C7}',
            description: "Gaufres dorees, moelleuses a l'interieur.",
            temps: 25,
            difficulte: 'facile',
            textures: ['moelleux', 'croustillant'],
            tags: ['creperie', 'gouter', 'convivial'],
            ingredients: ['Farine', 'Oeufs', 'Lait', 'Beurre fondu', 'Levure', 'Sucre'],
        },
        {
            id: 204,
            nom: 'Gateau au yaourt',
            emoji: '\u{1F370}',
            description: 'Gateau au yaourt moelleux et simple a preparer.',
            temps: 40,
            difficulte: 'très facile',
            textures: ['moelleux'],
            tags: ['gateau', 'familial', 'classique'],
            ingredients: ['Yaourt nature', 'Sucre', 'Farine', 'Huile', 'Oeufs', 'Levure'],
        },
        {
            id: 205,
            nom: 'Gateau a la noix de coco',
            emoji: '\u{1F965}',
            description: 'Gateau fondant parfume a la noix de coco.',
            temps: 40,
            difficulte: 'facile',
            textures: ['fondant'],
            tags: ['gateau', 'coco', 'patisserie'],
            ingredients: ['Noix de coco rapee', 'Oeufs', 'Sucre', 'Creme', 'Farine', 'Levure'],
        },
        {
            id: 206,
            nom: 'Pain cake moelleux',
            emoji: '\u{1F9C1}',
            description: 'Pain cake doux et moelleux pour le petit-dejeuner.',
            temps: 45,
            difficulte: 'facile',
            textures: ['moelleux'],
            tags: ['cake', 'brunch', 'patisserie'],
            ingredients: [
                'Farine', 'Oeufs', 'Sucre', 'Lait', 'Levure', 'Beurre',
                'Tartinade : cacahuete, miel, chocolat',
            ],
        },
        {
            id: 207,
            nom: 'Tiramisu maison',
            emoji: '\u{1F368}',
            description: 'Tiramisu maison cremeux aux biscuits imbibes.',
            temps: 25,
            difficulte: 'moyen',
            textures: ['cremeux'],
            tags: ['dessert froid', 'incontournable', 'patisserie'],
            ingredients: ['Mascarpone', 'Oeufs', 'Sucre', 'Biscuits cuillere', 'Cafe fort', 'Cacao en poudre'],
        }

        
    ],
    // A ajouter a la fin de RECETTES, apres desserts :
naim: [
    // -- BIBERONS --
    {
        id: 301,
        nom: 'Biberon lait tout seul',
        emoji: '🍼',
        description: 'Lait chaud ou tiede, simple et rassurant.',
        temps: 3,
        difficulte: 'très facile',
        categorie: 'biberon',
        tags: ['lait', 'simple'],
        ingredients: ['Lait bebe ou lait entier']
    },
    {
        id: 302,
        nom: 'Biberon chocolate',
        emoji: '🍼',
        description: 'Son biberon du matin avec une touche de cacao doux.',
        temps: 3,
        difficulte: 'très facile',
        categorie: 'biberon',
        tags: ['chocolat', 'matin'],
        ingredients: ['Lait', 'Chocolat en poudre bébé']
    },
    {
        id: 303,
        nom: 'Biberon avec céréales',
        emoji: '🍼',
        description: 'Lait enrichi de céréales bébé. Rassasiant, idéal avant la sieste.',
        temps: 3,
        difficulte: 'très facile',
        categorie: 'biberon',
        tags: ['céréales', 'rassasiant'],
        ingredients: ['Lait', 'Céréales bébé']
    },
    // -- GOUTERS --
    {
        id: 304,
        nom: 'Salade de fruits frais',
        emoji: '🍓',
        description: 'Petits dés de fruits mous selon la saison. Banane, fraise, poire, pastèque, mélon, mangue.',
        temps: 5,
        difficulte: 'très facile',
        categorie: 'gouter',
        tags: ['fruits', 'frais', 'sans cuisson'],
        ingredients: ['Banane', 'Fraises ou poire', 'Kiwi', 'Mangue', 'Pastèque', 'Melon'] 
    },
    {
        id: 305,
        nom: 'Yaourt nature, banane écrasée et pain',
        emoji: '🍌',
        description: 'Yaourt nature, banane bien mûre et bouts de pain.',
        temps: 3,
        difficulte: 'très facile',
        categorie: 'gouter',
        tags: ['yaourt', 'banane', 'classique'],
        ingredients: ['Yaourt nature', 'Banane mûre', 'Pain mou ou biscuits bébé']
    },
    {
        id: 306,
        nom: 'Yaourt avec biscuits à tremper',
        emoji: '🍪',
        description: 'Yaourt nature et biscuits. Il adore tremper.',
        temps: 2,
        difficulte: 'très facile',
        categorie: 'gouter',
        tags: ['yaourt', 'biscuits', 'classique'],
        ingredients: ['Yaourt nature', 'Biscuits bébé ou boudoirs']
    }
]
};