const RECETTES = {
	plats: [
		// Tous les plats sont prévus avec ingrédients halal.
		{
			id: 1,
			nom: 'Quiche poulet ou viande hâchée',
			emoji: '🥧',
			description: 'Quiche salée au poulet ou viande hâchée et petits pois, simple et rassasiante.',
			temps: 45,
			difficulte: 'facile',
			humeurs: ['fatigué', 'joyeux', 'amoureux'],
			tags: ['halal', 'four', 'familial'],
			ingredients: ['1 pâte brisée', '250 g de poulet halal', '150 g de petits pois', '3 œufs', '20 cl de crème', 'Sel, poivre'],
			etapes: ['Fais revenir le poulet en dés.', 'Mélange œufs, crème, sel et poivre.', 'Ajoute le poulet et les petits pois sur la pâte.', 'Enfourne 35 minutes à 180°C.']
		},
		{
			id: 2,
			nom: 'Poulet sauce petits pois & riz',
			emoji: '🍗',
			origine: 'Afrique de l’Est',
			description: 'Poulet halal mijoté avec petits pois, servi avec du riz.',
			temps: 35,
			difficulte: 'facile',
			humeurs: ['fatigué', 'stressé', 'sportif'],
			tags: ['halal', 'riz', 'mijoté'],
			ingredients: ['400 g de poulet halal', '1 oignon', '200 g de petits pois', '20 cl de coulis tomate', 'Épices douces', 'Riz cuit'],
			etapes: ['Fais revenir l’oignon et le poulet.', 'Ajoute le coulis et les épices.', 'Incorpore les petits pois puis mijote 15 minutes.', 'Sers chaud avec du riz.']
		},
		{
			id: 3,
			nom: 'Fah-fah djiboutien & riz',
			emoji: '🥣',
			origine: 'Djibouti',
			description: 'Soupe épicée djiboutienne au bœuf halal et légumes, avec riz.',
			temps: 50,
			difficulte: 'moyen',
			humeurs: ['curieux', 'stressé', 'fatigué'],
			tags: ['halal', 'tradition', 'réconfort'],
			ingredients: ['400 g de bœuf halal', '2 tomates', '1 carotte', '1 oignon', 'Bouillon', 'Riz blanc'],
			etapes: ['Fais revenir la viande et l’oignon.', 'Ajoute les légumes et le bouillon.', 'Mijote 35 minutes.', 'Sers en bol avec du riz à part.']
		},
		{
			id: 4,
			nom: 'Lentilles noires ou jaunes & pain',
			emoji: '🫘',
			origine: 'Maison',
			description: 'Lentilles bien assaisonnées, parfaites avec baguette ou pain.',
			temps: 30,
			difficulte: 'très facile',
			humeurs: ['fatigué', 'sportif', 'stressé'],
			tags: ['halal', 'économique', 'protéines'],
			ingredients: ['300 g de lentilles', '1 oignon', '1 gousse d’ail', '1 c. à soupe de tomate concentrée', 'Épices', 'Baguette'],
			etapes: ['Rince les lentilles.', 'Fais revenir oignon et ail.', 'Ajoute lentilles, eau et épices.', 'Laisse cuire puis sers avec pain.']
		},
		{
			id: 5,
			nom: 'Poisson & bananes plantains',
			emoji: '🐟',
			origine: 'Afrique',
			description: 'Poisson assaisonné servi avec bananes plantains dorées.',
			temps: 35,
			difficulte: 'moyen',
			humeurs: ['joyeux', 'curieux', 'amoureux'],
			tags: ['halal', 'plantain', 'complet'],
			ingredients: ['2 filets de poisson', '2 bananes plantains', '1 citron', 'Ail', 'Huile', 'Sel, poivre'],
			etapes: ['Assaisonne le poisson avec citron et ail.', 'Fais griller ou poêler le poisson.', 'Fais frire les rondelles de plantain.', 'Sers le tout bien chaud.']
		},
		{
			id: 6,
			nom: 'Viande halal & riz',
			emoji: '🍚',
			origine: 'Maison',
			description: 'Viande halal en sauce légère, servie sur un riz moelleux.',
			temps: 35,
			difficulte: 'facile',
			humeurs: ['sportif', 'fatigué', 'joyeux'],
			tags: ['halal', 'classique', 'familial'],
			ingredients: ['400 g de viande halal', '1 oignon', 'Épices', '200 g de riz', 'Huile', 'Sel'],
			etapes: ['Fais revenir la viande avec l’oignon.', 'Ajoute un peu d’eau et les épices.', 'Laisse mijoter 20 minutes.', 'Sers avec du riz nature.']
		},
		{
			id: 7,
			nom: 'Viande halal & pâtes',
			emoji: '🍖',
			origine: 'Maison',
			description: 'Viande halal mijotée et pâtes, un plat très apprécié des enfants.',
			temps: 30,
			difficulte: 'facile',
			humeurs: ['joyeux', 'fatigué', 'sportif'],
			tags: ['halal', 'pâtes', 'rapide'],
			ingredients: ['300 g de viande halal', '250 g de pâtes', '1 oignon', 'Sauce tomate', 'Épices', 'Huile'],
			etapes: ['Fais cuire les pâtes.', 'Prépare la sauce à la viande.', 'Mélange ou sers séparément.', 'Ajuste l’assaisonnement.']
		},
		{
			id: 8,
			nom: 'Pâtes bolognaise halal',
			emoji: '🍝',
			origine: 'Italie revisitée',
			description: 'Version halal de la bolognaise, riche et généreuse.',
			temps: 25,
			difficulte: 'facile',
			humeurs: ['fatigué', 'joyeux', 'amoureux'],
			tags: ['halal', 'tomate', 'incontournable'],
			ingredients: ['300 g de viande hachée halal', '250 g de pâtes', '400 g de sauce tomate', '1 oignon', 'Herbes', 'Huile d’olive'],
			etapes: ['Fais revenir l’oignon et la viande.', 'Ajoute la sauce tomate et les herbes.', 'Laisse mijoter 10 minutes.', 'Verse sur des pâtes cuites.']
		},
		{
			id: 9,
			nom: 'Haricots à la sauce',
			emoji: '🥘',
			origine: 'Afrique centrale',
			description: 'Haricots rouges en sauce tomate épicée, très nourrissants.',
			temps: 40,
			difficulte: 'facile',
			humeurs: ['sportif', 'stressé', 'fatigué'],
			tags: ['halal', 'végétal', 'batch cooking'],
			ingredients: ['400 g de haricots cuits', '1 oignon', '2 tomates', 'Ail', 'Épices', 'Huile'],
			etapes: ['Fais revenir l’oignon et l’ail.', 'Ajoute les tomates puis les haricots.', 'Assaisonne et laisse mijoter.', 'Sers avec du riz ou du pain.']
		},
		{
			id: 10,
			nom: 'Tacos halal maison',
			emoji: '🌮',
			origine: 'Street food',
			description: 'Tacos généreux au poulet ou bœuf halal avec sauce maison.',
			temps: 25,
			difficulte: 'facile',
			humeurs: ['joyeux', 'amoureux', 'curieux'],
			tags: ['halal', 'street food', 'convivial'],
			ingredients: ['Galettes tortillas', '300 g de viande halal', 'Fromage râpé', 'Frites', 'Sauce blanche', 'Salade'],
			etapes: ['Fais cuire la viande.', 'Garnis les galettes.', 'Plie et fais griller quelques minutes.', 'Sers bien chaud.']
		},
		{
			id: 11,
			nom: 'Pizza halal',
			emoji: '🍕',
			origine: 'Sidney & Hannah',
			description: 'Pizza maison garnie au poulet halal, légumes et fromage.',
			temps: 30,
			difficulte: 'facile',
			humeurs: ['joyeux', 'amoureux', 'fatigué'],
			tags: ['halal', 'partage', 'four'],
			ingredients: ['1 pâte à pizza', '200 g de poulet halal', 'Sauce tomate', 'Fromage', 'Poivron', 'Olives'],
			etapes: ['Étale la pâte.', 'Ajoute sauce et garniture.', 'Enfourne 12 à 15 minutes à 220°C.', 'Déguste chaude.']
		},
		{
			id: 12,
			nom: 'Burger halal',
			emoji: '🍔',
			origine: 'Sidney & Hannah',
			description: 'Burger maison au steak halal, croustillant et fondant.',
			temps: 20,
			difficulte: 'très facile',
			humeurs: ['joyeux', 'sportif', 'fatigué'],
			tags: ['halal', 'rapide', 'plaisir'],
			ingredients: ['Pains burger', '2 steaks halal', 'Fromage', 'Tomate', 'Salade', 'Sauce burger'],
			etapes: ['Fais cuire les steaks.', 'Toaste les pains.', 'Assemble avec garniture et sauce.', 'Sers avec frites.']
		},
		{
			id: 13,
			nom: 'Pâtes à la crème fraîche halal',
			emoji: '🍜',
			origine: 'Sidney & Hannah',
			description: 'Pâtes crémeuses avec émincés halal et herbes.',
			temps: 18,
			difficulte: 'très facile',
			humeurs: ['fatigué', 'amoureux', 'joyeux'],
			tags: ['halal', 'crémeux', 'express'],
			ingredients: ['250 g de pâtes', '200 g d’émincés halal', '20 cl de crème fraîche', 'Ail', 'Poivre', 'Parmesan'],
			etapes: ['Fais cuire les pâtes.', 'Fais revenir les émincés halal avec ail.', 'Ajoute crème et poivre.', 'Mélange avec les pâtes.']
		},
		{
			id: 14,
			nom: 'Nuggets de poulet halal',
			emoji: '🍗',
			origine: 'Sidney & Hannah',
			description: 'Nuggets croustillants au poulet halal, version maison.',
			temps: 22,
			difficulte: 'facile',
			humeurs: ['joyeux', 'fatigué', 'sportif'],
			tags: ['halal', 'croustillant', 'enfants'],
			ingredients: ['300 g de poulet halal', 'Farine', 'Œuf', 'Chapelure', 'Sel', 'Huile'],
			etapes: ['Coupe le poulet en morceaux.', 'Pane dans farine, œuf, chapelure.', 'Fais frire ou cuire au four.', 'Sers avec sauce.']
		},
		{
			id: 15,
			nom: 'Pondu',
			emoji: '🍃',
			origine: 'Congo',
			description: 'Feuilles de manioc longuement mijotées, plat traditionnel.',
			temps: 70,
			difficulte: 'moyen',
			humeurs: ['curieux', 'joyeux', 'amoureux'],
			tags: ['halal', 'tradition', 'africain'],
			ingredients: ['Feuilles de manioc', 'Huile de palme', 'Ail', 'Oignon', 'Bouillon', 'Piment doux'],
			etapes: ['Fais cuire les feuilles nettoyées.', 'Ajoute oignon, ail et bouillon.', 'Mijote longuement à feu doux.', 'Sers avec riz ou foufou.']
		},
		{
			id: 16,
			nom: 'Poisson salé',
			emoji: '🐠',
			origine: 'Afrique',
			description: 'Poisson salé en sauce tomate-oignons.',
			temps: 40,
			difficulte: 'moyen',
			humeurs: ['curieux', 'stressé', 'fatigué'],
			tags: ['halal', 'poisson', 'sauce'],
			ingredients: ['Poisson salé', '2 tomates', '1 oignon', 'Ail', 'Huile', 'Piment doux'],
			etapes: ['Dessale le poisson.', 'Prépare la sauce tomate-oignons.', 'Ajoute le poisson et laisse mijoter.', 'Sers avec du riz.']
		},
		{
			id: 17,
			nom: 'Poulet fumé sauce arachide',
			emoji: '🥜',
			origine: 'Afrique centrale',
			description: 'Poulet halal fumé avec une sauce arachide onctueuse.',
			temps: 55,
			difficulte: 'moyen',
			humeurs: ['amoureux', 'curieux', 'joyeux'],
			tags: ['halal', 'arachide', 'tradition'],
			ingredients: ['500 g de poulet fumé halal', '3 c. à soupe de pâte d’arachide', '1 oignon', 'Bouillon', 'Tomate', 'Épices'],
			etapes: ['Fais revenir l’oignon et la tomate.', 'Ajoute le poulet fumé.', 'Incorpore la pâte d’arachide et le bouillon.', 'Laisse mijoter et sers avec du riz.']
		},
		{
			id: 18,
			nom: 'Poisson au barbecue',
			emoji: '🔥',
			origine: 'Grillades',
			description: 'Poisson mariné puis grillé au barbecue.',
			temps: 30,
			difficulte: 'facile',
			humeurs: ['joyeux', 'sportif', 'curieux'],
			tags: ['halal', 'barbecue', 'été'],
			ingredients: ['Poisson entier', 'Citron', 'Ail', 'Persil', 'Huile', 'Sel'],
			etapes: ['Prépare une marinade citron-ail.', 'Badigeonne le poisson.', 'Fais griller des deux côtés.', 'Sers avec plantain ou salade.']
		},
		{
			id: 19,
			nom: 'Poulet au barbecue',
			emoji: '🍢',
			origine: 'Grillades',
			description: 'Poulet halal mariné puis grillé, croustillant dehors et tendre dedans.',
			temps: 40,
			difficulte: 'facile',
			humeurs: ['joyeux', 'amoureux', 'sportif'],
			tags: ['halal', 'barbecue', 'partage'],
			ingredients: ['600 g de poulet halal', 'Paprika', 'Ail', 'Huile', 'Citron', 'Sel, poivre'],
			etapes: ['Marine le poulet 20 minutes.', 'Grille au barbecue ou au four.', 'Retourne régulièrement.', 'Sers avec riz ou salade.']
		},
		{
			id: 20,
			nom: 'Haricots à la viande halal',
			emoji: '🍲',
			origine: 'Maison',
			description: 'Haricots mijotés avec viande halal, plat complet et généreux.',
			temps: 45,
			difficulte: 'moyen',
			humeurs: ['fatigué', 'sportif', 'stressé'],
			tags: ['halal', 'mijoté', 'familial'],
			ingredients: ['350 g de viande halal', '400 g de haricots', '1 oignon', 'Tomate', 'Ail', 'Épices'],
			etapes: ['Fais revenir la viande et l’oignon.', 'Ajoute tomate et assaisonnement.', 'Ajoute les haricots et un peu d’eau.', 'Mijote jusqu’à texture fondante.']
		}
	],

	entrees: [
		{
			id: 101,
			nom: 'Nems au poulet ou à la viande',
			emoji: '🥟',
			origine: 'Asie',
			description: 'Nems croustillants farcis au poulet halal ou viande halal.',
			temps: 30,
			difficulte: 'moyen',
			envies: ['festif', 'chaud'],
			tags: ['halal', 'apéro', 'croustillant'],
			ingredients: ['Galettes de riz', 'Poulet halal ou viande halal', 'Carotte', 'Vermicelles', 'Oignon', 'Épices'],
			etapes: ['Prépare la farce.', 'Roule les nems.', 'Fais frire ou cuire au four.', 'Sers avec une sauce pimentée.']
		},
		{
			id: 102,
			nom: 'Bricks au poulet ou à la viande',
			emoji: '🫓',
			origine: 'Maghreb',
			description: 'Feuilles de brick farcies et dorées, version halal.',
			temps: 20,
			difficulte: 'facile',
			envies: ['chaud', 'express', 'festif'],
			tags: ['halal', 'rapide', 'entrée chaude'],
			ingredients: ['Feuilles de brick', 'Poulet halal ou viande halal', 'Persil', 'Fromage', 'Œuf', 'Poivre'],
			etapes: ['Prépare la farce.', 'Garnis puis plie les bricks.', 'Fais dorer à la poêle.', 'Sers chaud.']
		},
		{
			id: 103,
			nom: 'Samoussas thon, viande ou poulet',
			emoji: '🔺',
			origine: 'Océan Indien',
			description: 'Petits triangles croustillants au thon, poulet halal ou viande halal.',
			temps: 28,
			difficulte: 'moyen',
			envies: ['festif', 'express'],
			tags: ['halal', 'finger food', 'partage'],
			ingredients: ['Feuilles de brick', 'Thon ou viande hachée halal ou poulet halal', 'Oignon', 'Persil', 'Épices', 'Huile'],
			etapes: ['Prépare la farce.', 'Plie les triangles.', 'Fais frire ou cuire au four.', 'Sers à l’apéritif.']
		}
	],

	desserts: [
		{
			id: 201,
			nom: 'Crêpes maison',
			emoji: '🥞',
			origine: 'France',
			description: 'Crêpes fines et moelleuses, parfaites pour le goûter.',
			temps: 20,
			difficulte: 'très facile',
			textures: ['crémeux'],
			tags: ['goûter', 'classique', 'familial'],
			ingredients: ['250 g de farine', '3 œufs', '50 cl de lait', '1 sachet sucre vanillé', '1 c. à soupe d’huile', '1 pincée de sel'],
			etapes: ['Mélange tous les ingrédients.', 'Laisse reposer 20 minutes.', 'Fais cuire en fines couches à la poêle.', 'Sers avec sucre ou pâte à tartiner.']
		},
		{
			id: 202,
			nom: 'Gaufres dorées',
			emoji: '🧇',
			origine: 'Belgique',
			description: 'Gaufres croustillantes à l’extérieur, tendres à l’intérieur.',
			temps: 25,
			difficulte: 'facile',
			textures: ['croustillant', 'crémeux'],
			tags: ['goûter', 'sucré', 'convivial'],
			ingredients: ['250 g de farine', '2 œufs', '40 cl de lait', '70 g de beurre fondu', '1 sachet levure', 'Sucre'],
			etapes: ['Prépare la pâte à gaufres.', 'Laisse reposer 15 minutes.', 'Verse dans le gaufrier chaud.', 'Déguste avec topping au choix.']
		},
		{
			id: 203,
			nom: 'Gâteau au yaourt',
			emoji: '🍰',
			origine: 'Maison',
			description: 'Gâteau moelleux ultra simple, idéal avec les enfants.',
			temps: 40,
			difficulte: 'très facile',
			textures: ['crémeux'],
			tags: ['facile', 'four', 'familial'],
			ingredients: ['1 yaourt nature', '2 pots de sucre', '3 pots de farine', '1/2 pot d’huile', '3 œufs', '1 sachet levure'],
			etapes: ['Mélange les ingrédients.', 'Verse dans un moule beurré.', 'Enfourne 30 minutes à 180°C.', 'Laisse tiédir avant de servir.']
		},
		{
			id: 204,
			nom: 'Gâteau au coco',
			emoji: '🥥',
			origine: 'Tropiques',
			description: 'Gâteau parfumé à la noix de coco, doux et fondant.',
			temps: 38,
			difficulte: 'facile',
			textures: ['crémeux'],
			tags: ['coco', 'moelleux', 'dessert'],
			ingredients: ['200 g de coco râpée', '3 œufs', '150 g de sucre', '20 cl de crème', '80 g de farine', '1 sachet levure'],
			etapes: ['Fouette œufs et sucre.', 'Ajoute coco, crème et farine.', 'Verse dans un moule.', 'Enfourne 30 minutes à 180°C.']
		},
		{
			id: 205,
			nom: 'Boulettes spéculoos enrobées chocolat',
			emoji: '🍫',
			origine: 'Maison',
			description: 'Petites bouchées au spéculoos trempées dans le chocolat.',
			temps: 20,
			difficulte: 'facile',
			textures: ['chocolaté', 'croustillant'],
			tags: ['sans four', 'gourmand', 'snack'],
			ingredients: ['200 g de spéculoos', '80 g de fromage frais', '150 g de chocolat noir', '1 c. à café de miel', 'Noix de coco râpée', 'Piques en bois'],
			etapes: ['Mixe les spéculoos et mélange avec fromage frais.', 'Forme des boulettes puis réserve au frais.', 'Fais fondre le chocolat.', 'Enrobe les boulettes et laisse figer.']
		},
		{
			id: 206,
			nom: 'Cake nature (pain cake)',
			emoji: '🍞',
			origine: 'Maison',
			description: 'Cake doux et parfumé, parfait pour le petit-déjeuner.',
			temps: 45,
			difficulte: 'facile',
			textures: ['croustillant', 'crémeux'],
			tags: ['cake', 'brunch', 'familial'],
			ingredients: ['250 g de farine', '3 œufs', '120 g de sucre', '10 cl de lait', '1 sachet levure', '80 g de beurre'],
			etapes: ['Mélange les ingrédients jusqu’à pâte lisse.', 'Verse dans un moule à cake.', 'Enfourne 35 minutes à 180°C.', 'Laisse refroidir avant découpe.']
		},
		{
			id: 207,
			nom: 'Tiramisu',
			emoji: '🍨',
			origine: 'Italie',
			description: 'Dessert crémeux au mascarpone et biscuits imbibés.',
			temps: 25,
			difficulte: 'moyen',
			textures: ['crémeux', 'chocolaté'],
			tags: ['dessert froid', 'café', 'incontournable'],
			ingredients: ['250 g de mascarpone', '3 œufs', '80 g de sucre', 'Biscuits cuillère', 'Café fort', 'Cacao en poudre'],
			etapes: ['Prépare la crème mascarpone.', 'Trempe les biscuits dans le café.', 'Monte les couches crème/biscuits.', 'Réserve 4 heures au frais puis saupoudre de cacao.']
		}
	]
};
